version: '3'
services:

  postgres-service-ghcnd:
    image: postgres:latest
    container_name: postgresql-ghcnd
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - "./data:/var/lib/postgresql/data:rw"

    # Only needed when connecting directly from the host. Other containers with access to ghcnd network still connect
    ports:
      - "5432:5432"
    networks:
      - default
      - ghcnd

  pgadmin-ghcnd:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-ghcnd
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8085:80"

networks:
  ghcnd:
    name: ghcnd